name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install pytest pytest-cov
        # Additional dependency for nibabel (used by nilearn)
        pip install nibabel
        # Additional UI dependencies
        pip install matplotlib
        pip install seaborn
        
    - name: Install package in development mode
      run: |
        pip install -e .
        
    - name: Debug imports
      run: |
        python -c "import sys; print(sys.path)"
        python -c "import os; print(os.listdir('.'))"
        python -c "import os; print(os.listdir('./src'))"
        
    - name: Test with pytest
      run: |
        # Run tests with simplified collection to isolate issues
        python -m pytest src/data_processing/ -v
        python -m pytest src/input_format/ -v
        python -m pytest src/visualization/ -v
        
    - name: Run coverage
      run: |
        python -m pytest src --cov=src
        
    - name: Generate coverage report
      run: |
        python -m pytest src --cov=src --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 